### ISSUE TITLE
Bug - 'Send' functionality broken with genesis account 

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#388] opened 2022-10-31 04:45 UTC
**Description**
Broken 'Send' UX/UI with specific genesis account(s)

**Additional Context**
- account: haytcmjrgige
- not yet reproducible with other genesis accounts 

**Screenshots**
![image](https://user-images.githubusercontent.com/6848910/198932528-3cab6289-15f3-4b68-be20-8c2ce6bcfab4.png)

**Comment by WikusKriek** [comment] 2022-11-04 11:06
![image](https://user-images.githubusercontent.com/41372145/199958214-86f78b5e-1cfa-41f0-a099-9c7bfd1bf559.png)
I was able to do this on mainnet @donnyquixotic. Not able to duplicate the issue.

**Comment by WikusKriek** [comment] 2022-11-04 11:07
![image](https://user-images.githubusercontent.com/41372145/199958484-7aa47e67-7603-413c-b505-5309c235f3c0.png)

**Comment by karynemayer** [comment] 2022-11-04 20:24
Closing it because is not reproducible anymore

**Closed by karynemayer** 2022-11-04 20:24 UTC
Labels: 🐛 Bug, 🔬 Needs Grooming
