### ISSUE TITLE
Transaction showed in two different formats and switched between them

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/open-block-explorer#682] opened 2023-03-29 21:17 UTC
## Overview
When looking at a staking resources transaction, the same transaction is shown in two ways. After some time, it switches to one, then it switches back again to the other.

![Screenshot 2023-03-29 at 14 13 01](https://user-images.githubusercontent.com/2939354/228669538-006af15a-1f85-4749-b498-e562226f0961.png)
![Screenshot 2023-03-29 at 14 12 52](https://user-images.githubusercontent.com/2939354/228669539-e7b67888-7d4b-4f21-8bd5-18ef25260ee1.png)

transaction of the images, using testnet: `2c881d31204067622774468346e7623813a149792941b3fe77f9a5b014131a14`

## Acceptance criteria
- The transaction should be shown in a single format
- The same format must be used throughout all transactions
- The format should not change into any other one

**Comment by donnyquixotic** [comment] 2023-10-18 22:17
Closing as unable to reproduce

**Closed by donnyquixotic** 2023-10-18 22:17 UTC
Labels: 🐛 Bug
