### ISSUE TITLE
Incorrect CPU/Net balance

### ISSUE THREAD

**Issue by EJSG** [telosnetwork/open-block-explorer#565] opened 2023-02-06 21:02 UTC
## Description

For this account which has no CPU or NET balance, the balance is shown as `20` when it should be `0`
![Image](https://user-images.githubusercontent.com/11837820/217084928-8be7f3b3-151e-4810-9e89-a7220335f098.png)

**Comment by donnyquixotic** [comment] 2023-02-09 03:19
@EJSG which account is this? I'm having issues reproducing

**Comment by EJSG** [comment] 2023-02-09 17:11
@donnyquixotic sorry, on testnet its `eztestnet123`

**Comment by donnyquixotic** [comment] 2023-02-09 20:41
closing as not a bug, (resources are delegated on testnet account creation)

**Closed by donnyquixotic** 2023-02-09 20:41 UTC
Labels: 🐛 Bug
