### ISSUE TITLE
Verify rendering of transactions for msig with multiple transfers

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/open-block-explorer#513] opened 2023-01-09 22:00 UTC
**Description**
For msig with multiple transfer actions to the same address, the receiving address shows all incoming transactions but the sending address shows only one. Verify rendering of transactions for sending account.

Sending account example: https://explorer.telos.net/account/haytcmjrgige

**Comment by jaegerfe** [comment] 2023-01-24 21:25
I believe this one is a duplicated of #439. @karynemayer @donnyquixotic

**Comment by karynemayer** [comment] 2023-01-27 00:09
Duplicate of https://github.com/telosnetwork/open-block-explorer/issues/439, indeed

**Closed by karynemayer** 2023-01-27 00:09 UTC
Labels: 🐛 Bug, 👯 Duplicated
